/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uco_sdd_spring15_dj_drmr_record_Lame */

#ifndef _Included_edu_uco_sdd_spring15_dj_drmr_record_Lame
#define _Included_edu_uco_sdd_spring15_dj_drmr_record_Lame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uco_sdd_spring15_dj_drmr_record_Lame
 * Method:    log
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_edu_uco_sdd_spring15_dj_1drmr_record_Lame_log
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
