/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uco_sdd_spring15_dj_drmr_record_Encoder_Builder */

#ifndef _Included_edu_uco_sdd_spring15_dj_drmr_record_Encoder_Builder
#define _Included_edu_uco_sdd_spring15_dj_drmr_record_Encoder_Builder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
